language: c

compiler:  
    - gcc
    - clang

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script:
 - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ../mini_jvm && cmake --build . && cmake --build . --target minijvm
